version: 2                                                                                                 
                                                                                                             
sources:                                                                                                   
    - name: ecommerce_raw                                                                                    
      database: ALL_DATA                                                                                     
      schema: ECOMMERCE_RAW
      tables:
        - name: customers
        - name: products
        - name: orders
        - name: order_items